os: Visual Studio 2017
version: 2019.1.{build}
clone_depth: 5
install:
- set REPODIR=%CD%
- set /P RDM_VERSION=<version.txt
- git clone -q --depth=5 --branch=%RDM_VERSION% https://github.com/uglide/RedisDesktopManager.git C:\projects\redisdesktopmanager
- set SRCDIR=C:\projects\RedisDesktopManager
- set QTDIR=C:\Qt\5.9\msvc2017_64
- set PATH=%QTDIR%\bin;%PATH%
- cd %SRCDIR%
- git describe --abbrev=0 --tags
- git rev-parse --short HEAD
- git submodule update --init --recursive
- call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" x86_amd64
- qmake -v

build_script:
- cd %SRCDIR%
- cd ./3rdparty/qredisclient/
- 7z.exe x "%REPODIR%\deps.zip"
- del /F qredisclient.lib
- cd %SRCDIR%
- python ./build/utils/set_version.py %RDM_VERSION% > ./src/version.h
- cd %SRCDIR%/3rdparty
- nuget install zlib-msvc14-x64 -Version 1.2.11.7795
- cd qredisclient/3rdparty/hiredis
- git apply -v ../hiredis-win.patch
- cd %SRCDIR%/src
- lrelease rdm.pro
- qmake CONFIG+=release
- nmake /S /NOLOGO release
- cd %SRCDIR%
- copy /y .\bin\windows\release\rdm.exe .\build\windows\installer\resources\rdm.exe
- copy /y .\3rdparty\qredisclient\botan.dll .\build\windows\installer\resources\botan.dll
- copy /y .\3rdparty\qredisclient\3rdparty\windows\rmt_openssl.1.1.0.3\build\native\bin\v140\Win32\Release\dynamic\libcrypto-1_1.dll .\build\windows\installer\resources\libcrypto-1_1.dll	
- copy /y .\3rdparty\qredisclient\3rdparty\windows\rmt_openssl.1.1.0.3\build\native\bin\v140\Win32\Release\dynamic\libssl-1_1.dll .\build\windows\installer\resources\libssl-1_1.dll	
- 7z.exe x "%REPODIR%\python37-deps.zip" -o.\build\windows\installer\resources\
- cd build/windows/installer/resources/
- windeployqt --no-angle --no-opengl-sw --no-compiler-runtime --no-translations --release --force --qmldir %SRCDIR%/src/qml rdm.exe
- rmdir /S /Q .\platforminputcontexts
- rmdir /S /Q .\qmltooling
- rmdir /S /Q .\QtGraphicalEffects
- del /Q  .\imageformats\qtiff.dll
- del /Q  .\imageformats\qwebp.dll
- C:\Python37\python.exe -m pip install -t . -r %SRCDIR%/src/py/requirements.txt
- cd %SRCDIR%
- call "C:\\Program Files (x86)\\NSIS\\makensis.exe" /V1 /DVERSION=%RDM_VERSION%.0.0 ./build/windows/installer/installer.nsi
artifacts:
- path: build/windows/installer/redis-desktop-manager-*.exe
